/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dice.java
 *
 * Created on 2010-nov-09, 15:46:08
 */
package xeed;

import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;

/**
 *
 * @author Erik
 */
public class frmDiceoWoD extends javax.swing.JFrame {

    DefaultListModel jListModel = new DefaultListModel();

    /** Creates new form dice */
    public frmDiceoWoD() {

        initComponents();
        try {
            ArrayList<Image> images = new ArrayList(0);
            images.add(ImageIO.read(this.getClass().getResource("/icon.png")));
            images.add(ImageIO.read(this.getClass().getResource("/package_go.png")));
            this.setIconImages(images);
        } catch (IOException e) {
        }
        lstResult.setModel(jListModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResult = new javax.swing.JList();
        lblSuccess = new javax.swing.JLabel();
        lblBotches = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblResults = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDice = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDifficulty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRoll = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        chkSpecialized = new javax.swing.JCheckBox();

        jTextField1.setText("Unnamed Instance");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unnamed Instance");
        setLocationByPlatform(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lstResult.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstResultKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstResult);

        lblSuccess.setText("Successes:");

        lblBotches.setText("Botches:");

        lblResults.setText("Result:");

        jLabel4.setText("Quantity");

        txtDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiceActionPerformed(evt);
            }
        });
        txtDice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiceKeyPressed(evt);
            }
        });

        txtType.setText("10");
        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });
        txtType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTypeKeyPressed(evt);
            }
        });

        jLabel5.setText("Sides");

        txtDifficulty.setText("6");
        txtDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDifficultyActionPerformed(evt);
            }
        });
        txtDifficulty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDifficultyKeyPressed(evt);
            }
        });

        jLabel6.setText("Difficulty");

        btnRoll.setText("Roll");
        btnRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollActionPerformed(evt);
            }
        });

        txtName.setText("Unnamed Instance");
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        chkSpecialized.setText("Specialised");
        chkSpecialized.setToolTipText("Dice that rolls the highest value (normally 10) are rerolled and the original sucess is still counted.");
        chkSpecialized.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chkSpecializedKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBotches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSuccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDice, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRoll, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtType, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addGap(26, 26, 26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addGap(8, 8, 8))
                            .addComponent(txtDifficulty)
                            .addComponent(chkSpecialized)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSuccess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBotches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResults)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDice)
                    .addComponent(txtType)
                    .addComponent(txtDifficulty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoll)
                    .addComponent(chkSpecialized))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiceActionPerformed
   
    }//GEN-LAST:event_txtDiceActionPerformed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
     
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDifficultyActionPerformed
        
    }//GEN-LAST:event_txtDifficultyActionPerformed

    private void btnRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollActionPerformed

        try {

            Random RndGen = new Random();

            int intType = Integer.parseInt(txtType.getText());
            int intDice = Integer.parseInt(txtDice.getText());

            jListModel.clear();
            ArrayList<Integer> results = new ArrayList(0);

            for (int x = 0; x < intDice; x++) {
                int intRoll = RndGen.nextInt(intType) + 1;
                jListModel.addElement(intRoll);
                results.add(intRoll);
                if (chkSpecialized.isSelected() && intRoll == intType) {
                    intDice++;
                }
            }

            lblSuccess.setText("Successes:");
            lblBotches.setText("Botches:");
            lblResults.setText("Result:");

            lblSuccess.repaint();
            lblBotches.repaint();
            lblResults.repaint();

            /*Ifall txtDiff är cp så blir det exception här men inga hard feelings ;)*/
            int intDiff = Integer.parseInt(txtDifficulty.getText());

            int intSuc = 0;
            int intBotch = 0;
            for (int z = 0; z < results.size(); z++) {
                if (results.get(z) >= intDiff) {
                    intSuc++;
                } else if (results.get(z) == 1) {
                    intBotch++;
                }
            }

            int intResult = intSuc - intBotch;

            lblSuccess.setText("Successes: " + intSuc);
            lblBotches.setText("Botches: " + intBotch);
            if (intBotch > intSuc) {
                lblResults.setText("Result: Botch (" + intResult + ")");
            } else if (intResult == 0) {
                lblResults.setText("Result: Failure (" + intResult + ")");
            } else {
                lblResults.setText("Result: Success (" + intResult + ")");
            }

            lblSuccess.repaint();
            lblBotches.repaint();
            lblResults.repaint();

        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnRollActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
     
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtDiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiceKeyPressed
        if (evt.getKeyCode() == 10) {
            btnRollActionPerformed(null);
        }
    }//GEN-LAST:event_txtDiceKeyPressed

    private void txtTypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTypeKeyPressed
        if (evt.getKeyCode() == 10) {
            btnRollActionPerformed(null);
        }
    }//GEN-LAST:event_txtTypeKeyPressed

    private void txtDifficultyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDifficultyKeyPressed
        if (evt.getKeyCode() == 10) {
            btnRollActionPerformed(null);
        }
    }//GEN-LAST:event_txtDifficultyKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == 10) {
            btnRollActionPerformed(null);
        }
    }//GEN-LAST:event_formKeyPressed

    private void lstResultKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstResultKeyPressed
        if (evt.getKeyCode() == 10) {
            btnRollActionPerformed(null);
        }
    }//GEN-LAST:event_lstResultKeyPressed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        this.setTitle(txtName.getText());
    }//GEN-LAST:event_txtNameKeyReleased

    private void chkSpecializedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chkSpecializedKeyPressed
        if (evt.getKeyCode() == 10) {
            btnRollActionPerformed(null);
        }
    }//GEN-LAST:event_chkSpecializedKeyPressed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRoll;
    private javax.swing.JCheckBox chkSpecialized;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBotches;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblSuccess;
    private javax.swing.JList lstResult;
    private javax.swing.JTextField txtDice;
    private javax.swing.JTextField txtDifficulty;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
