/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package templates;

/**
 *
 * @author Erik
 */
public class SectionPanel extends javax.swing.JPanel {

   /**
    * Creates new form pnlSection
    */
   public SectionPanel() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      pnlActionArea = new javax.swing.JPanel();

      javax.swing.GroupLayout pnlActionAreaLayout = new javax.swing.GroupLayout(pnlActionArea);
      pnlActionArea.setLayout(pnlActionAreaLayout);
      pnlActionAreaLayout.setHorizontalGroup(pnlActionAreaLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 367, Short.MAX_VALUE));
      pnlActionAreaLayout.setVerticalGroup(pnlActionAreaLayout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 380, Short.MAX_VALUE));

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(pnlActionArea, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));
      layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(pnlActionArea, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addContainerGap()));
   } // </editor-fold>//GEN-END:initComponents
     // Variables declaration - do not modify//GEN-BEGIN:variables

   public javax.swing.JPanel pnlActionArea;
   // End of variables declaration//GEN-END:variables
}
