/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package templates;

import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author Erik
 */
public class CharacterPanel extends javax.swing.JPanel {

   public ArrayList<Component> items = new ArrayList(0);

   public CharacterPanel() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      setLayout(new java.awt.GridLayout(1, 0));
   }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
